### PR TITLE
add mirror server

### PR DESCRIPTION
**Pull request by ramazansancar**

### CODE REVIEW

**Comment by mchangrh** [comment]
wget download is not supported, lartza doesn't offer rsync :(

**Comment by ramazansancar** [comment]
Sad :/

**Comment by ramazansancar** [comment]
You can obtain the data written on the Sponsor Block website from the mirror, then the source is invalid. Is it true?

**Comment by mchangrh** [comment]
You can download it via wget and plop it in, but this was intended for delta updates via rsync

**Pull request closed without merging**
